name: Trigger auto deployment for container-app-3mkatsxgmpvgu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-3mkatsxgmpvgu-AutoDeployTrigger-a5f35d33-9f12-49cf-a540-0ffbb10254b2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP3MKATSXGMPVGU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP3MKATSXGMPVGU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP3MKATSXGMPVGU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP3MKATSXGMPVGU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP3MKATSXGMPVGU_REGISTRY_PASSWORD }}
          containerAppName: container-app-3mkatsxgmpvgu
          resourceGroup: 20240508expressa4c5
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


